name: Update README Stats

on:
  schedule:
    - cron: '0 0 * * *' # Si aggiorna da solo ogni notte a mezzanotte
  workflow_dispatch: # Ti permette di avviarlo a mano quando vuoi

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: thanhhaudev/github-stats@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_METRICS: "COMMITS,PAD,LANGUAGES"
